version: '2'
services:
    gateway-app:
        image: gateway
        external_links:
            - gateway-mariadb:mariadb
            # Uncomment to have Cassandra working with the gateway
            # - gateway-cassandra:cassandra
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/gateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    gateway-mariadb:
        extends:
            file: mariadb.yml
            service: gateway-mariadb
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra-cluster.yml
        #     service: gateway-cassandra
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
